#!/usr/bin/env bash
set -eu -o pipefail

# Run static code style analysis in a docker container

# This presumes that you have pointed your docker client at minikube and
# you've built the pipeline image.

function pathnorm {
    # Normalize the path
    local abspath
    abspath="$(cd "$1" || exit 1; pwd)"
    echo "${abspath#/cygdrive}"
}

# Configuration can be found in .flake8
docker run --rm -v "$(pathnorm "$PWD"):/code" fast-api-prototype-pipeline:local flake8 components
