# Values here will overwrite values.yaml defaults. These values are used when deploying locally to minikube
# Application configuration
app:
  uvicorn:
    workers: 1
    autoreload: true
  liveness:
    use: false
  readiness:
    use: false

# Configurations for setting up apm tracing
apm:
  datadog_env: local

