apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    project: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
    name: {{ .Chart.Name }}
    githash: {{ .Values.deploy.imageTag | quote }}
# Create key - value entries in the data map that other files can look up
# Load them into the environment by using configMapRef in the deploy.yaml file
data:
  REDIS_CREATE: {{ .Values.redis.create | quote }}
  ELASTICSEARCH_CREATE: {{ .Values.elasticsearch.create | quote }}
  ELASTICSEARCH_POPULATE: {{ .Values.elasticsearch.populate | quote }}
  ELASTICSEARCH_HOST: {{ .Chart.Name }}-elasticsearch
  ELASTICSEARCH_PORT: {{ .Values.elasticsearch.port | quote }}
# uvicorn environment variables
  UVICORN_WORKERS: {{ .Values.app.uvicorn.workers | quote }}
  UVICORN_AUTORELOAD: {{ and .Values.deploy.withMount .Values.app.uvicorn.autoreload | ternary "true" "false" | quote }}
  UVICORN_PORT: {{ .Values.app.uvicorn.port | quote }}
  UVICORN_DOMAIN_SOCKET: {{ .Values.app.uvicorn.domain_socket | quote }}
# datadog environment variables
  APM_ENABLED: {{ .Values.apm.enable | quote }}
  DATADOG_SERVICE_NAME: {{ .Chart.Name | quote }}
  DATADOG_ENV: {{ .Values.apm.datadog_env | quote }}
  DATADOG_TRACE_AGENT_HOSTNAME: {{ .Values.apm.datadog_trace_agent_hostname | quote }}
